version: "3.9" 

services:
  # DATABASE Container
  jtaraya-yolo-database:
    build:
      context: ./database          
      dockerfile: Dockerfile      
    image: jtaraya-yolo-database:v1.0.0
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_INITDB_ROOT_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}
    container_name: jtaraya-yolo-database
    args:
      - buildversion=1.0.0
    ports:
      - "27017:27017"
    volumes:
      - mongo-database:/data/db
    env_file:
      - .env

volumes:
  mongo-database:
    driver: local
