- name: Backend Deployment Block
  block:
    - name: Build backend image
      community.docker.docker_image:
        name: "{{ backend_image }}"
        build:
          path: "{{ app_directory }}/backend"
          pull: yes
        source: build
        force_source: yes

    - name: Stop existing container
      community.docker.docker_container:
        name: "{{ backend_container_name }}"
        state: absent
      ignore_errors: yes

    - name: Deploy backend container
      community.docker.docker_container:
        name: "{{ backend_container_name }}"
        image: "{{ backend_image }}"
        state: started
        restart_policy: always
        networks:
          - name: "{{ docker_network_name }}"
        ports:
          - "{{ backend_port }}:5000"
        env:
          MONGODB_URI: "{{ mongodb_connection_string }}"
          PORT: "5000"
        links:
          - "{{ mongodb_container_name }}:mongodb"

    - name: Wait for backend
      wait_for:
        host: localhost
        port: "{{ backend_port }}"
        delay: 10
        timeout: 120

  rescue:
    - debug:
        msg: "Backend deployment failed"
    - fail:
        msg: "Backend deployment failed"
