- name: Application Setup Block
  block:
    - name: Install Git
      apt:
        name: git
        state: present

    - name: Remove existing directory
      file:
        path: "{{ app_directory }}"
        state: absent

    - name: Create application directory
      file:
        path: "{{ app_directory }}"
        state: directory
        owner: "{{ app_user }}"
        group: "{{ app_user }}"

    - name: Clone repository
      git:
        repo: "{{ github_repo }}"
        dest: "{{ app_directory }}"
        version: "{{ github_branch }}"
        force: yes
      become_user: "{{ app_user }}"

    - name: Verify clone
      stat:
        path: "{{ app_directory }}/README.md"
      register: repo_check

    - name: Fail if not cloned
      fail:
        msg: "Repository clone failed"
      when: not repo_check.stat.exists

  rescue:
    - debug:
        msg: "App setup failed"
    - fail:
        msg: "App setup failed"
